# Generated by Django 5.0.3 on 2024-04-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': [('can_delete', 'Can delete')]},
        ),
    ]
